# Generated by Django 4.1.7 on 2023-02-19 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchedulePH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('dataD', models.CharField(max_length=25, verbose_name='Дата')),
                ('mode', models.CharField(max_length=30, verbose_name='Режим')),
            ],
        ),
    ]
