# Generated by Django 4.1.7 on 2023-02-19 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_teachersph'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeachersMath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75, verbose_name='ФИО')),
                ('description', models.CharField(max_length=256, verbose_name='Должность')),
                ('dataD', models.CharField(max_length=256, verbose_name='Ученая степень')),
                ('mode', models.CharField(max_length=256, verbose_name='Ссылка на фотографию')),
            ],
            options={
                'verbose_name': 'Преподавателя',
                'verbose_name_plural': 'Преподаватели по математике',
            },
        ),
        migrations.AlterModelOptions(
            name='teachersph',
            options={'verbose_name': 'Преподавателя', 'verbose_name_plural': 'Преподаватели по физике'},
        ),
    ]
