# Generated by Django 4.1.7 on 2023-02-19 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_teachersit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75, verbose_name='ФИО')),
                ('description', models.CharField(max_length=256, verbose_name='Описание')),
                ('mode', models.CharField(max_length=256, verbose_name='Ссылка на фотографию')),
            ],
        ),
    ]
